### ISSUE TITLE
readInt and readInteger don't handle negative numbers

### ISSUE THREAD

**Issue by cdsmith** [AndrasKovacs/flatparse#17]
They should either be documented to only accept non-negative integers, or they should parse negative integers.  Either way is fine.  In #16, I made the change to document in the haddock comment that they can only read non-negative integers.  If you prefer the other choice, let me know and I will take a look.

Discovered while writing tests.

**Comment by raehik** [comment]
I think it would be sensible to have `readWord / readNatural` which only parses the ASCII digits, and `readInt / readInteger` which also parses an optional sign prefix. That would match [`Data.ByteString.Char8.readInteger`](https://hackage.haskell.org/package/bytestring-0.11.3.1/docs/src/Data.ByteString.Char8.html#readInteger)'s behaviour.

I have some work on a fork that clarifies their usage and the invariants worked with internally: https://github.com/raehik/flatparse/pull/1/files#diff-b85bff6e45bdf8699c3bd32004a018a6ecaf4c8965767a021541f4d26e5d23f0R61-R87 . I also rename them to `readAsciiWord` and `readAsciiNatural` respectively - I think putting ASCII in the names is sensible, since otherwise one could read them as "read a [machine] integer", which isn't what they do.

**Comment by raehik** [comment]
Docs fix applied in #22 - cheers.
